[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
custom_error = "7KU5Q7YaEgbu5fu6ohfUaxY7wm78r4iBuFjiqNKSsTUc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 'tests/**/*.ts'"
